apiVersion: v1
kind: Service
metadata:
  labels:
    app: hbase-region
  name: hbase-region
spec:
  ports:
  - name: "60010"
    port: 60010
  - name: "60020"
    port: 60020
  - name: "ssh"
    port: 22
  selector:
    app: hbase-region
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-region
  labels:
    app: hbase-region
spec:
  serviceName: hbase-region
  replicas: 1
  selector:
    matchLabels:
      app: hbase-region
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hbase-region
    spec:
      containers:
      - name: hbase-region
        image: oisp/hbase:{{ .Values.tag }}
        resources:
          limits:
            memory: 200M
            cpu: 100m
        env:
        - name: HBASE_MASTER
          value: hbase-master
        - name: ZOOKEEPER
          value: zookeeper:2181
        - name: HDFS_NAMENODE
          value: hdfs-namenode
        command: ["/bin/bash", "/opt/entrypoint-region.sh"]
        ports:
        - containerPort: 60010
        - containerPort: 60020
        - containerPort: 22
      imagePullSecrets:
      - name: dockercred
