apiVersion: v1
kind: Service
metadata:
  labels:
    app: hbase-master
  name: hbase-master
spec:
  ports:
  - name: "8080"
    port: 8080
  - name: "9090"
    port: 9090
  - name: "9095"
    port: 9095
  - name: "16010"
    port: 16010
  - name: "60000"
    port: 60000
  selector:
    app: hbase-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-master
  labels:
    app: hbase-master
spec:
  serviceName: hbase-master
  replicas: 1
  selector:
    matchLabels:
      app: hbase-master
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      containers:
      - name: hbase-master
        image: oisp/hbase:{{ .Values.tag }}
        resources:
          limits:
            memory: 200M
            cpu: 100m
        env:
        - name: REGIONSERVERS
          value: hbase-region
        - name: ZOOKEEPER
          value: zookeeper
        - name: HDFS_NAMENODE
          value: hdfs-namenode
        command: ["/bin/bash", "/opt/wait-for-it.sh", "hdfs-namenode:8020", "-t", "300", "--", "bash", "/opt/wait-for-it.sh", "zookeeper:2181", "-t", "300", "--", "/opt/entrypoint.sh"]
        ports:
        - containerPort: 9090
        - containerPort: 8080
        - containerPort: 60000
        - containerPort: 16010
        - containerPort: 9095
        volumeMounts:
        - mountPath: /data
          name: hbase-data
        readinessProbe:
          tcpSocket:
            port: 9090
      imagePullSecrets:
      - name: dockercred
      hostname: hbase
      volumes:
      - name: hbase-data
        persistentVolumeClaim:
          claimName: hbase-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbase-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
