apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - name: kafka
    port: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: bitnami/kafka:1.1.1
        resources:
          requests:
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENERS
          value: "yes"
        - name: KAFKA_LISTENERS
          value: "LISTENER_BOB://0.0.0.0:9092,LISTENER_FRED://0.0.0.0:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "LISTENER_BOB://kafka:9092,LISTENER_FRED://localhost:9093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "LISTENER_BOB"
        ports:
        - containerPort: 9092
        readinessProbe:
          tcpSocket:
            port: 9092
